import {topics} from './seo-topics.mjs';
import fs from 'node:fs';
export function buildGuides({page,heading,card,products,esc}) {
 const tiles=topics.map(t=>`<a class="guide-card" href="/guides/${t.slug}/"><img src="/assets/${t.image}" alt="${esc(t.label)} — BLUE DELTA" loading="lazy" width="300" height="230"><div><h3>${t.label}</h3><p>${t.description}</p><span class="textlink">Lire le guide →</span></div></a>`).join('');
 page('guides/','Guides techniques : refroidissement, eau et antitartre','Les guides BLUE DELTA pour choisir vos produits de refroidissement industriel, eau déminéralisée et nettoyage antitartre en Algérie.',`${heading('Guides techniques','Comprendre votre application pour choisir le bon produit.')}<section class="section"><div class="wrap"><div class="guide-grid">${tiles}</div></div></section>`);
 for(const t of topics){
  const related=products.filter(p=>t.products.includes(p.id));
  page(`guides/${t.slug}/`,t.title,t.description,`<section class="page-head"><div class="wrap"><nav class="breadcrumb" aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/guides/">Guides techniques</a><span>/</span><span>${t.label}</span></nav><div class="eyebrow">BLUE DELTA · Guide technique</div><h1>${t.title}</h1><p>${t.intro}</p></div></section><section class="section"><div class="wrap guide-layout"><article class="guide-prose">${t.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}<section><h2>Questions fréquentes</h2>${t.faq.map(([q,a])=>`<details class="guide-faq"><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><p class="fine">Les caractéristiques contractuelles du produit figurent dans sa fiche technique et sa fiche de données de sécurité (FDS). Demandez les documents applicables à la référence retenue.</p></article><aside class="guide-aside"><img src="/assets/${t.image}" alt="${esc(t.label)} BLUE DELTA" width="340" height="340"><h2>Votre besoin technique</h2><p>Application, matériaux, températures, volume : transmettez ces éléments à notre équipe à Ouled Moussa, Boumerdès.</p><a class="btn full" href="/contact/">Demander un conseil</a><a class="textlink" href="/partenariat/">Devenir distributeur →</a><h3>À lire également</h3>${topics.filter(x=>x.slug!==t.slug).map(x=>`<a href="/guides/${x.slug}/">${x.label}</a>`).join('')}</aside></div></section><section class="section gray"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Le catalogue BLUE DELTA</div><h2>Références à découvrir</h2></div><a class="textlink" href="/produits/">Tout le catalogue →</a></div><div class="product-grid" data-guide-products="${t.products.join(',')}">${related.map(card).join('')}</div></div></section>`);
 }
 fs.mkdirSync('seo',{recursive:true});
 const quote=s=>'"'+String(s).replaceAll('"','""')+'"';
 fs.writeFileSync('seo/mots-cles.csv','\uFEFFThème;Mot-clé;Page cible;Statut\r\n'+topics.flatMap(t=>t.keywords.map(k=>[t.label,k,'https://bluedelta.dz/guides/'+t.slug+'/','Candidat éditorial — volume non mesuré'].map(quote).join(';'))).join('\r\n'));
}
export {topics};
